const domainSchema = `
CREATE TABLE IF NOT EXISTS sys_org (
  id INTEGER PRIMARY KEY AUTOINCREMENT, org_code TEXT NOT NULL UNIQUE, org_name TEXT NOT NULL,
  org_type TEXT NOT NULL, status TEXT NOT NULL DEFAULT '正常', created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS sys_user (
  id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT NOT NULL UNIQUE, display_name TEXT NOT NULL,
  org_id INTEGER NOT NULL, status TEXT NOT NULL DEFAULT '正常', created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY(org_id) REFERENCES sys_org(id)
);
CREATE TABLE IF NOT EXISTS sys_role (
  id INTEGER PRIMARY KEY AUTOINCREMENT, role_code TEXT NOT NULL UNIQUE, role_name TEXT NOT NULL,
  description TEXT, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS sys_user_role (id INTEGER PRIMARY KEY AUTOINCREMENT,user_id INTEGER NOT NULL,role_id INTEGER NOT NULL,UNIQUE(user_id,role_id),FOREIGN KEY(user_id) REFERENCES sys_user(id),FOREIGN KEY(role_id) REFERENCES sys_role(id));
CREATE TABLE IF NOT EXISTS sys_permission (id INTEGER PRIMARY KEY AUTOINCREMENT,permission_code TEXT NOT NULL UNIQUE,permission_name TEXT NOT NULL,module TEXT NOT NULL,action TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS sys_role_permission (id INTEGER PRIMARY KEY AUTOINCREMENT,role_id INTEGER NOT NULL,permission_id INTEGER NOT NULL,UNIQUE(role_id,permission_id),FOREIGN KEY(role_id) REFERENCES sys_role(id),FOREIGN KEY(permission_id) REFERENCES sys_permission(id));
CREATE TABLE IF NOT EXISTS sys_login_log (id INTEGER PRIMARY KEY AUTOINCREMENT,user_id INTEGER,login_time TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,client_address TEXT,result TEXT NOT NULL,FOREIGN KEY(user_id) REFERENCES sys_user(id));
CREATE TABLE IF NOT EXISTS sys_operation_log (id INTEGER PRIMARY KEY AUTOINCREMENT,role_code TEXT NOT NULL,org_id INTEGER,user_name TEXT,module TEXT NOT NULL,action TEXT NOT NULL,target_type TEXT,target_id INTEGER,detail TEXT,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);

CREATE TABLE IF NOT EXISTS tds_space (id INTEGER PRIMARY KEY AUTOINCREMENT,space_code TEXT NOT NULL UNIQUE,space_name TEXT NOT NULL,operator_org_id INTEGER NOT NULL,status TEXT NOT NULL DEFAULT '运行中',created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(operator_org_id) REFERENCES sys_org(id));
CREATE TABLE IF NOT EXISTS tds_space_member (id INTEGER PRIMARY KEY AUTOINCREMENT,space_id INTEGER NOT NULL,org_id INTEGER NOT NULL,member_type TEXT NOT NULL,status TEXT NOT NULL DEFAULT '已入驻',joined_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,UNIQUE(space_id,org_id),FOREIGN KEY(space_id) REFERENCES tds_space(id),FOREIGN KEY(org_id) REFERENCES sys_org(id));
CREATE TABLE IF NOT EXISTS tds_connector (id INTEGER PRIMARY KEY AUTOINCREMENT,connector_no TEXT NOT NULL UNIQUE,connector_name TEXT NOT NULL,org_id INTEGER NOT NULL,system_name TEXT NOT NULL,connection_type TEXT NOT NULL,status TEXT NOT NULL DEFAULT '在线',last_heartbeat TEXT,service_count INTEGER NOT NULL DEFAULT 0,epcis_status TEXT NOT NULL DEFAULT '正常',error_count INTEGER NOT NULL DEFAULT 0,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(org_id) REFERENCES sys_org(id));
CREATE TABLE IF NOT EXISTS tds_data_source (id INTEGER PRIMARY KEY AUTOINCREMENT,source_name TEXT NOT NULL,connector_id INTEGER NOT NULL,source_type TEXT NOT NULL,source_system TEXT NOT NULL,sync_mode TEXT NOT NULL,update_frequency TEXT,status TEXT NOT NULL DEFAULT '正常',event_conversion INTEGER NOT NULL DEFAULT 0,last_sync_at TEXT,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(connector_id) REFERENCES tds_connector(id));
CREATE TABLE IF NOT EXISTS tds_data_resource (id INTEGER PRIMARY KEY AUTOINCREMENT,resource_no TEXT NOT NULL UNIQUE,resource_name TEXT NOT NULL,org_id INTEGER NOT NULL,source_id INTEGER,service_type TEXT NOT NULL,sensitivity_level TEXT NOT NULL DEFAULT '内部',update_mode TEXT,epcis_enabled INTEGER NOT NULL DEFAULT 0,status TEXT NOT NULL DEFAULT '已登记',created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(org_id) REFERENCES sys_org(id),FOREIGN KEY(source_id) REFERENCES tds_data_source(id));
CREATE TABLE IF NOT EXISTS tds_data_product (id INTEGER PRIMARY KEY AUTOINCREMENT,product_no TEXT NOT NULL UNIQUE,product_name TEXT NOT NULL,org_id INTEGER NOT NULL,resource_id INTEGER,product_type TEXT NOT NULL,service_mode TEXT NOT NULL,support_query INTEGER NOT NULL DEFAULT 0,support_subscribe INTEGER NOT NULL DEFAULT 0,allow_download INTEGER NOT NULL DEFAULT 0,status TEXT NOT NULL DEFAULT '已上架',created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(org_id) REFERENCES sys_org(id),FOREIGN KEY(resource_id) REFERENCES tds_data_resource(id));
CREATE TABLE IF NOT EXISTS tds_access_request (id INTEGER PRIMARY KEY AUTOINCREMENT,request_no TEXT NOT NULL UNIQUE,applicant_org_id INTEGER NOT NULL,provider_org_id INTEGER NOT NULL,product_id INTEGER NOT NULL,demand_id INTEGER,purpose TEXT NOT NULL,status TEXT NOT NULL DEFAULT '草稿',review_comment TEXT,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(applicant_org_id) REFERENCES sys_org(id),FOREIGN KEY(provider_org_id) REFERENCES sys_org(id),FOREIGN KEY(product_id) REFERENCES tds_data_product(id));
CREATE TABLE IF NOT EXISTS tds_authorization (id INTEGER PRIMARY KEY AUTOINCREMENT,authorization_no TEXT NOT NULL UNIQUE,request_id INTEGER NOT NULL,provider_org_id INTEGER NOT NULL,consumer_org_id INTEGER NOT NULL,product_id INTEGER NOT NULL,demand_id INTEGER,status TEXT NOT NULL DEFAULT '生效中',valid_from TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,valid_to TEXT,max_calls INTEGER NOT NULL DEFAULT 1000,remaining_calls INTEGER NOT NULL DEFAULT 1000,allow_query INTEGER NOT NULL DEFAULT 1,allow_subscribe INTEGER NOT NULL DEFAULT 0,allow_download INTEGER NOT NULL DEFAULT 0,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(request_id) REFERENCES tds_access_request(id),FOREIGN KEY(provider_org_id) REFERENCES sys_org(id),FOREIGN KEY(consumer_org_id) REFERENCES sys_org(id),FOREIGN KEY(product_id) REFERENCES tds_data_product(id));
CREATE TABLE IF NOT EXISTS tds_authorization_item (id INTEGER PRIMARY KEY AUTOINCREMENT,authorization_id INTEGER NOT NULL,field_name TEXT NOT NULL,field_rule TEXT,data_scope TEXT,FOREIGN KEY(authorization_id) REFERENCES tds_authorization(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS tds_data_usage_log (id INTEGER PRIMARY KEY AUTOINCREMENT,authorization_id INTEGER,product_id INTEGER,consumer_org_id INTEGER,user_name TEXT,use_purpose TEXT,call_method TEXT,result_count INTEGER NOT NULL DEFAULT 0,call_status TEXT NOT NULL,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(authorization_id) REFERENCES tds_authorization(id),FOREIGN KEY(product_id) REFERENCES tds_data_product(id));
CREATE TABLE IF NOT EXISTS tds_conversion_rule (id INTEGER PRIMARY KEY AUTOINCREMENT,rule_no TEXT NOT NULL UNIQUE,rule_name TEXT NOT NULL,org_id INTEGER NOT NULL,connector_id INTEGER NOT NULL,source_object TEXT NOT NULL,source_status TEXT NOT NULL,target_event_type TEXT NOT NULL,biz_step TEXT,biz_status TEXT,version TEXT NOT NULL DEFAULT 'V1.0',status TEXT NOT NULL DEFAULT '启用',created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(org_id) REFERENCES sys_org(id),FOREIGN KEY(connector_id) REFERENCES tds_connector(id));
CREATE TABLE IF NOT EXISTS tds_mapping_field (id INTEGER PRIMARY KEY AUTOINCREMENT,rule_id INTEGER NOT NULL,source_field TEXT NOT NULL,target_field TEXT NOT NULL,transform_expression TEXT,required INTEGER NOT NULL DEFAULT 0,FOREIGN KEY(rule_id) REFERENCES tds_conversion_rule(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS tds_conversion_task (id INTEGER PRIMARY KEY AUTOINCREMENT,task_no TEXT NOT NULL UNIQUE,rule_id INTEGER NOT NULL,source_record_no TEXT,status TEXT NOT NULL DEFAULT '待转换',created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(rule_id) REFERENCES tds_conversion_rule(id));
CREATE TABLE IF NOT EXISTS tds_conversion_record (id INTEGER PRIMARY KEY AUTOINCREMENT,record_no TEXT NOT NULL UNIQUE,rule_id INTEGER,source_record_no TEXT,source_status TEXT,epcis_event_no TEXT,event_type TEXT,transport_order_id INTEGER,transport_task_id INTEGER,validation_result TEXT,publish_status TEXT,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(rule_id) REFERENCES tds_conversion_rule(id));
CREATE TABLE IF NOT EXISTS tds_conversion_error (id INTEGER PRIMARY KEY AUTOINCREMENT,error_no TEXT NOT NULL UNIQUE,org_id INTEGER,rule_id INTEGER,error_type TEXT NOT NULL,error_message TEXT NOT NULL,status TEXT NOT NULL DEFAULT '待处理',created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS tds_epcis_event (id INTEGER PRIMARY KEY AUTOINCREMENT,event_no TEXT NOT NULL UNIQUE,event_type TEXT NOT NULL,biz_step TEXT,biz_status TEXT,event_time TEXT NOT NULL,org_id INTEGER,transport_order_id INTEGER,transport_task_id INTEGER,location_name TEXT,payload_json TEXT,publish_status TEXT NOT NULL DEFAULT '已发布',created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS tds_event_subscription (id INTEGER PRIMARY KEY AUTOINCREMENT,subscription_no TEXT NOT NULL UNIQUE,consumer_org_id INTEGER NOT NULL,product_id INTEGER,event_types TEXT NOT NULL,callback_type TEXT NOT NULL,status TEXT NOT NULL DEFAULT '启用',created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS tds_event_delivery_log (id INTEGER PRIMARY KEY AUTOINCREMENT,subscription_id INTEGER,event_id INTEGER,delivery_time TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,delivery_result TEXT NOT NULL,retry_count INTEGER NOT NULL DEFAULT 0);

CREATE TABLE IF NOT EXISTS mm_transport_demand (id INTEGER PRIMARY KEY AUTOINCREMENT,demand_no TEXT NOT NULL UNIQUE,trader_org_id INTEGER NOT NULL,cargo_name TEXT NOT NULL,quantity_tons REAL NOT NULL,origin TEXT NOT NULL,destination TEXT NOT NULL,expected_departure TEXT,expected_arrival TEXT,cost_preference TEXT,time_preference TEXT,transport_requirements TEXT,status TEXT NOT NULL DEFAULT '草稿',created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(trader_org_id) REFERENCES sys_org(id));
CREATE TABLE IF NOT EXISTS mm_capacity_resource (id INTEGER PRIMARY KEY AUTOINCREMENT,resource_no TEXT NOT NULL UNIQUE,org_id INTEGER NOT NULL,resource_type TEXT NOT NULL,resource_name TEXT NOT NULL,available_capacity TEXT NOT NULL,service_scope TEXT,status TEXT NOT NULL DEFAULT '可用',created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(org_id) REFERENCES sys_org(id));
CREATE TABLE IF NOT EXISTS mm_transport_scheme (id INTEGER PRIMARY KEY AUTOINCREMENT,scheme_no TEXT NOT NULL UNIQUE,demand_id INTEGER NOT NULL,scheme_name TEXT NOT NULL,route_summary TEXT NOT NULL,estimated_hours REAL NOT NULL,estimated_cost REAL NOT NULL,risk_level TEXT NOT NULL,recommendation_reason TEXT,status TEXT NOT NULL DEFAULT '待确认',created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(demand_id) REFERENCES mm_transport_demand(id));
CREATE TABLE IF NOT EXISTS mm_scheme_segment (id INTEGER PRIMARY KEY AUTOINCREMENT,scheme_id INTEGER NOT NULL,segment_no INTEGER NOT NULL,segment_type TEXT NOT NULL,carrier_org_id INTEGER NOT NULL,origin TEXT NOT NULL,destination TEXT NOT NULL,planned_start TEXT,planned_end TEXT,estimated_cost REAL,status TEXT NOT NULL DEFAULT '待确认',UNIQUE(scheme_id,segment_no),FOREIGN KEY(scheme_id) REFERENCES mm_transport_scheme(id) ON DELETE CASCADE,FOREIGN KEY(carrier_org_id) REFERENCES sys_org(id));
CREATE TABLE IF NOT EXISTS mm_transport_order (id INTEGER PRIMARY KEY AUTOINCREMENT,order_no TEXT NOT NULL UNIQUE,demand_id INTEGER NOT NULL,scheme_id INTEGER NOT NULL,trader_org_id INTEGER NOT NULL,cargo_name TEXT NOT NULL,quantity_tons REAL NOT NULL,origin TEXT NOT NULL,destination TEXT NOT NULL,estimated_arrival TEXT,total_cost REAL,status TEXT NOT NULL DEFAULT '待确认',created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(demand_id) REFERENCES mm_transport_demand(id),FOREIGN KEY(scheme_id) REFERENCES mm_transport_scheme(id));
CREATE TABLE IF NOT EXISTS mm_order_party (id INTEGER PRIMARY KEY AUTOINCREMENT,order_id INTEGER NOT NULL,org_id INTEGER NOT NULL,party_role TEXT NOT NULL,UNIQUE(order_id,org_id,party_role),FOREIGN KEY(order_id) REFERENCES mm_transport_order(id) ON DELETE CASCADE,FOREIGN KEY(org_id) REFERENCES sys_org(id));
CREATE TABLE IF NOT EXISTS mm_task (id INTEGER PRIMARY KEY AUTOINCREMENT,task_no TEXT NOT NULL UNIQUE,order_id INTEGER NOT NULL,segment_no INTEGER NOT NULL,task_type TEXT NOT NULL,responsible_org_id INTEGER NOT NULL,resource_id INTEGER,origin TEXT NOT NULL,destination TEXT NOT NULL,planned_start TEXT,planned_end TEXT,actual_start TEXT,actual_end TEXT,progress INTEGER NOT NULL DEFAULT 0,status TEXT NOT NULL DEFAULT '待确认',created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(order_id) REFERENCES mm_transport_order(id),FOREIGN KEY(responsible_org_id) REFERENCES sys_org(id));
CREATE TABLE IF NOT EXISTS mm_transport_event (id INTEGER PRIMARY KEY AUTOINCREMENT,event_no TEXT NOT NULL UNIQUE,order_id INTEGER NOT NULL,task_id INTEGER,event_type TEXT NOT NULL,event_time TEXT NOT NULL,location_name TEXT,source_org_id INTEGER,epcis_event_id INTEGER,description TEXT,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS mm_exception (id INTEGER PRIMARY KEY AUTOINCREMENT,exception_no TEXT NOT NULL UNIQUE,order_id INTEGER,task_id INTEGER,exception_type TEXT NOT NULL,reporter_org_id INTEGER,responsible_org_id INTEGER,description TEXT NOT NULL,handling_comment TEXT,status TEXT NOT NULL DEFAULT '待处理',created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS mm_data_reference (id INTEGER PRIMARY KEY AUTOINCREMENT,scheme_id INTEGER NOT NULL,authorization_id INTEGER NOT NULL,product_id INTEGER NOT NULL,provider_org_id INTEGER NOT NULL,influence TEXT NOT NULL,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
`;

const roleSeed = [
  ['platform','平台管理员','企业用户、平台监管与审计'],['trader','贸易商业务负责人','数据申请、方案与订单'],['fleet','公路货运调度员','公路数据与任务'],['railway','铁路调度员','铁路数据与任务'],['port','港口协同员','港口协同数据与任务'],['shipping','船商调度员','船期舱位与海运任务']
];
const orgSeed = [
  ['ORG-PLATFORM','北粮南运通道运营中心','平台运营方'],['ORG-TRADER','北沃粮食贸易有限公司','粮食贸易商'],['ORG-FLEET','黑龙江畅运物流','车队企业'],['ORG-RAIL','沈阳局货运中心','铁路企业'],['ORG-PORT','营口港集团','港口企业'],['ORG-SHIP','北方粮运航运','船商企业']
];

function one(database, sql, ...params){return database.prepare(sql).get(...params)}
function insertIgnore(database, sql, ...params){database.prepare(sql).run(...params)}

export function initializeDomainSchema(database){
  database.exec(domainSchema);
  for(const row of orgSeed)insertIgnore(database,'INSERT OR IGNORE INTO sys_org(org_code,org_name,org_type) VALUES(?,?,?)',...row);
  for(const row of roleSeed)insertIgnore(database,`INSERT INTO sys_role(role_code,role_name,description) VALUES(?,?,?)
    ON CONFLICT(role_code) DO UPDATE SET role_name=excluded.role_name,description=excluded.description,updated_at=CURRENT_TIMESTAMP`,...row);
  for(const [index,[roleCode,roleName]] of roleSeed.entries()){
    const org=one(database,'SELECT id FROM sys_org WHERE org_code=?',orgSeed[index][0]);
    const role=one(database,'SELECT id FROM sys_role WHERE role_code=?',roleCode);
    insertIgnore(database,'INSERT OR IGNORE INTO sys_user(username,display_name,org_id) VALUES(?,?,?)',`${roleCode}@blny.cn`,roleName.replace(/管理员|业务负责人|调度员|协同员/,'')||roleName,org.id);
    const user=one(database,'SELECT id FROM sys_user WHERE username=?',`${roleCode}@blny.cn`);
    insertIgnore(database,'INSERT OR IGNORE INTO sys_user_role(user_id,role_id) VALUES(?,?)',user.id,role.id);
  }
  const platformOrg=one(database,"SELECT id FROM sys_org WHERE org_code='ORG-PLATFORM'");
  insertIgnore(database,"INSERT OR IGNORE INTO tds_space(space_code,space_name,operator_org_id) VALUES('BLNY-TDS-001','北粮南运可信数据空间',?)",platformOrg.id);
  const space=one(database,"SELECT id FROM tds_space WHERE space_code='BLNY-TDS-001'");
  for(const [code,,type] of orgSeed){const org=one(database,'SELECT id FROM sys_org WHERE org_code=?',code);insertIgnore(database,'INSERT OR IGNORE INTO tds_space_member(space_id,org_id,member_type) VALUES(?,?,?)',space.id,org.id,type)}
  const providers=[
    ['FLEET','ORG-FLEET','车队TMS连接器','车队TMS','API','公路可用运力','API查询','公路可用运力查询','公路运力','68辆散粮车 / 5,000吨','绥化—哈尔滨'],
    ['RAIL','ORG-RAIL','铁路运力连接器','班列计划系统','数据库','铁路班列和车皮','API查询','铁路班列和车皮查询','铁路运力','100节 / 5,000吨','哈尔滨—营口港'],
    ['PORT','ORG-PORT','港口协同连接器','港口能力接口','API','港口作业能力','API查询','港口作业能力查询','港口能力','卸车+筒仓+装船 5,000吨','营口港'],
    ['SHIP','ORG-SHIP','船期舱位连接器','船期管理系统','API','船期和剩余舱位','API查询','船期舱位查询','船期舱位','散粮舱位 5,000吨','营口港—广东目的港']
  ];
  for(const p of providers){
    const [key,orgCode,connectorName,systemName,connType,resourceName,serviceType,productName,capacityType,capacity,scope]=p;
    const org=one(database,'SELECT id FROM sys_org WHERE org_code=?',orgCode);
    insertIgnore(database,'INSERT OR IGNORE INTO tds_connector(connector_no,connector_name,org_id,system_name,connection_type,last_heartbeat,service_count) VALUES(?,?,?,?,?,CURRENT_TIMESTAMP,2)',`CON-${key}-001`,connectorName,org.id,systemName,connType);
    const connector=one(database,'SELECT id FROM tds_connector WHERE connector_no=?',`CON-${key}-001`);
    insertIgnore(database,'INSERT OR IGNORE INTO tds_data_source(id,source_name,connector_id,source_type,source_system,sync_mode,update_frequency,event_conversion,last_sync_at) VALUES(?,?,?,?,?,?,?,?,CURRENT_TIMESTAMP)',100+providers.indexOf(p),systemName,connector.id,connType,systemName,'增量同步','5分钟',1);
    const source=one(database,'SELECT id FROM tds_data_source WHERE id=?',100+providers.indexOf(p));
    insertIgnore(database,'INSERT OR IGNORE INTO tds_data_resource(resource_no,resource_name,org_id,source_id,service_type,sensitivity_level,update_mode,status) VALUES(?,?,?,?,?,?,?,?)',`RES-${key}-001`,resourceName,org.id,source.id,serviceType,'内部','实时','已发布');
    const resource=one(database,'SELECT id FROM tds_data_resource WHERE resource_no=?',`RES-${key}-001`);
    insertIgnore(database,'INSERT OR IGNORE INTO tds_data_product(product_no,product_name,org_id,resource_id,product_type,service_mode,support_query,status) VALUES(?,?,?,?,?,?,1,?)',`PROD-${key}-001`,productName,org.id,resource.id,'资源查询',serviceType,'已上架');
    insertIgnore(database,'INSERT OR IGNORE INTO mm_capacity_resource(resource_no,org_id,resource_type,resource_name,available_capacity,service_scope) VALUES(?,?,?,?,?,?)',`CAP-${key}-001`,org.id,capacityType,productName,capacity,scope);
    insertIgnore(database,'INSERT OR IGNORE INTO tds_conversion_rule(rule_no,rule_name,org_id,connector_id,source_object,source_status,target_event_type,biz_step,biz_status) VALUES(?,?,?,?,?,?,?,?,?)',`RULE-${key}-001`,`${capacityType}状态事件转换`,org.id,connector.id,'运输任务状态','已完成',`${capacityType}完成事件`,'shipping','in_transit');
  }
  const trader=one(database,"SELECT id FROM sys_org WHERE org_code='ORG-TRADER'");
  insertIgnore(database,"INSERT OR IGNORE INTO mm_transport_demand(demand_no,trader_org_id,cargo_name,quantity_tons,origin,destination,expected_departure,expected_arrival,cost_preference,time_preference,transport_requirements,status) VALUES('DEM-2026-0001',?,'玉米',5000,'黑龙江绥化粮库','广东目的港','2026-08-06 08:00','2026-08-13 18:00','综合成本最低','准时到达','公路+铁路+港口+海运；全程事件可追踪','草稿')",trader.id);
}
