import { Router } from 'express';

class HttpError extends Error{constructor(status,message){super(message);this.status=status}}
const providers=['fleet','railway','port','shipping'];
const allRoles=['platform','trader',...providers];
const field=(name,label,type='text',required=false,options=[])=>({name,label,type,required,options});
const resources={
  organizations:{table:'sys_org',title:'企业管理',search:['org_code','org_name','org_type','status'],read:allRoles,create:['platform'],update:['platform'],delete:['platform'],fields:[field('org_code','企业编码','text',true),field('org_name','企业名称','text',true),field('org_type','企业类型','select',true,['平台运营方','粮食贸易商','车队企业','铁路企业','港口企业','船商企业']),field('status','状态','select',true,['正常','停用'])]},
  users:{table:'sys_user',title:'用户管理',search:['username','display_name','status'],read:['platform'],create:['platform'],update:['platform'],delete:['platform'],fields:[field('username','登录账号','text',true),field('display_name','姓名','text',true),field('org_id','所属企业ID','number',true),field('status','状态','select',true,['正常','停用'])]},
  roles:{table:'sys_role',title:'角色权限',search:['role_code','role_name','description'],read:['platform'],create:['platform'],update:['platform'],delete:['platform'],fields:[field('role_code','角色编码','text',true),field('role_name','角色名称','text',true),field('description','角色说明')]},
  connectors:{table:'tds_connector',title:'连接器',search:['connector_no','connector_name','system_name','status'],read:allRoles,create:providers,update:providers,delete:providers,owner:'org_id',fields:[field('connector_no','连接器编号','text',true),field('connector_name','连接器名称','text',true),field('system_name','对接系统','text',true),field('connection_type','连接方式','select',true,['API','数据库','消息队列','文件']),field('status','状态','select',true,['在线','离线','异常','停用'])]},
  dataSources:{table:'tds_data_source',title:'数据来源',search:['source_name','source_type','source_system','status'],read:allRoles,create:providers,update:providers,delete:providers,ownerVia:'connector',fields:[field('source_name','数据源名称','text',true),field('connector_id','连接器ID','number',true),field('source_type','数据源类型','select',true,['API接口','数据库','消息队列','文件上传','模拟数据源']),field('source_system','对接系统','text',true),field('sync_mode','同步方式','text',true),field('update_frequency','更新频率'),field('event_conversion','事件转换','boolean'),field('status','状态','select',true,['正常','异常','停用'])]},
  dataResources:{table:'tds_data_resource',title:'数据资源',search:['resource_no','resource_name','service_type','status'],read:allRoles,create:providers,update:providers,delete:providers,owner:'org_id',fields:[field('resource_no','资源编号','text',true),field('resource_name','资源名称','text',true),field('source_id','数据源ID','number'),field('service_type','服务类型','select',true,['API查询','结果数据','文件服务','EPCIS事件订阅']),field('sensitivity_level','敏感等级','select',true,['公开','内部','敏感']),field('update_mode','更新方式'),field('epcis_enabled','EPCIS转换','boolean'),field('status','状态','select',true,['草稿','已登记','已发布','停用'])]},
  dataProducts:{table:'tds_data_product',title:'数据产品',search:['product_no','product_name','product_type','service_mode','status'],read:allRoles,create:providers,update:providers,delete:providers,owner:'org_id',publicRead:true,fields:[field('product_no','产品编号','text',true),field('product_name','产品名称','text',true),field('resource_id','数据资源ID','number'),field('product_type','产品类型','select',true,['资源查询','事件订阅','结果数据','文件服务']),field('service_mode','服务方式','text',true),field('support_query','支持查询','boolean'),field('support_subscribe','支持订阅','boolean'),field('allow_download','允许下载','boolean'),field('status','状态','select',true,['草稿','待审核','已上架','已下架'])]},
  requests:{table:'tds_access_request',title:'数据使用申请',search:['request_no','purpose','status','review_comment'],read:allRoles,create:['trader'],update:['trader'],delete:['trader'],scope:{trader:'applicant_org_id',provider:'provider_org_id'},fields:[field('request_no','申请编号','text',true),field('provider_org_id','数据提供方ID','number',true),field('product_id','数据产品ID','number',true),field('demand_id','运输需求ID','number'),field('purpose','使用目的','text',true)]},
  authorizations:{table:'tds_authorization',title:'数据授权',search:['authorization_no','status','valid_to'],read:allRoles,create:[],update:[],delete:[],scope:{trader:'consumer_org_id',provider:'provider_org_id'},fields:[]},
  conversionRules:{table:'tds_conversion_rule',title:'EPCIS转换规则',search:['rule_no','rule_name','source_object','target_event_type','status'],read:allRoles,create:providers,update:providers,delete:providers,owner:'org_id',fields:[field('rule_no','规则编号','text',true),field('rule_name','规则名称','text',true),field('connector_id','连接器ID','number',true),field('source_object','源数据对象','text',true),field('source_status','源业务状态','text',true),field('target_event_type','目标事件类型','text',true),field('biz_step','EPCIS业务步骤'),field('biz_status','EPCIS业务状态'),field('version','版本'),field('status','状态','select',true,['启用','停用'])]},
  conversionRecords:{table:'tds_conversion_record',title:'转换记录',search:['record_no','source_record_no','event_type','validation_result','publish_status'],read:allRoles,create:[],update:[],delete:[],scope:{provider:'conversionRule'},fields:[]},
  conversionErrors:{table:'tds_conversion_error',title:'转换异常',search:['error_no','error_type','error_message','status'],read:allRoles,create:providers,update:providers,delete:providers,owner:'org_id',fields:[field('error_no','异常编号','text',true),field('rule_id','规则ID','number'),field('error_type','异常类型','text',true),field('error_message','异常说明','text',true),field('status','状态','select',true,['待处理','处理中','已处理','已忽略'])]},
  usageLogs:{table:'tds_data_usage_log',title:'使用记录',search:['user_name','use_purpose','call_method','call_status'],read:allRoles,create:[],update:[],delete:[],scope:{trader:'consumer_org_id',provider:'productProvider'},fields:[]},
  demands:{table:'mm_transport_demand',title:'运输需求',search:['demand_no','cargo_name','origin','destination','status'],read:allRoles,create:['trader'],update:['trader'],delete:['trader'],owner:'trader_org_id',fields:[field('demand_no','需求编号','text',true),field('cargo_name','货物名称','text',true),field('quantity_tons','数量（吨）','number',true),field('origin','起运地','text',true),field('destination','目的地','text',true),field('expected_departure','期望发运时间','datetime-local'),field('expected_arrival','期望到达时间','datetime-local'),field('cost_preference','成本偏好'),field('time_preference','时效偏好'),field('transport_requirements','运输要求','textarea')]},
  capacities:{table:'mm_capacity_resource',title:'运力资源',search:['resource_no','resource_type','resource_name','service_scope','status'],read:allRoles,create:providers,update:providers,delete:providers,owner:'org_id',publicRead:true,fields:[field('resource_no','资源编号','text',true),field('resource_type','资源类型','text',true),field('resource_name','资源名称','text',true),field('available_capacity','可用能力','text',true),field('service_scope','服务范围'),field('status','状态','select',true,['可用','已锁定','停用'])]},
  schemes:{table:'mm_transport_scheme',title:'联运方案',search:['scheme_no','scheme_name','route_summary','risk_level','status'],read:allRoles,create:[],update:[],delete:[],scope:{trader:'demand'},fields:[]},
  orders:{table:'mm_transport_order',title:'运输订单',search:['order_no','cargo_name','origin','destination','status'],read:allRoles,create:[],update:[],delete:[],scope:{trader:'trader_org_id',provider:'party'},fields:[]},
  tasks:{table:'mm_task',title:'分段任务',search:['task_no','task_type','origin','destination','status'],read:allRoles,create:[],update:[],delete:[],scope:{provider:'responsible_org_id',trader:'orderTrader'},fields:[]},
  events:{table:'mm_transport_event',title:'运输事件',search:['event_no','event_type','location_name','description'],read:allRoles,create:[],update:[],delete:[],scope:{provider:'source_org_id',trader:'eventOrderTrader'},fields:[]},
  exceptions:{table:'mm_exception',title:'异常协同',search:['exception_no','exception_type','description','status'],read:allRoles,create:['trader',...providers],update:['trader',...providers],delete:[],scope:{trader:'reporter_org_id',provider:'responsibleOrReporter'},fields:[field('exception_no','异常编号','text',true),field('order_id','运输订单ID','number'),field('task_id','分段任务ID','number'),field('exception_type','异常类型','select',true,['车辆故障','道路拥堵','班列晚点','港口拥堵','装船延误','船期变更','舱位不足','数据异常','事件转换失败']),field('responsible_org_id','责任企业ID','number'),field('description','异常说明','textarea',true),field('handling_comment','处理意见','textarea'),field('status','状态','select',true,['待处理','处理中','已关闭'])]},
  operationLogs:{table:'sys_operation_log',title:'操作日志',search:['role_code','user_name','module','action','detail'],read:['platform'],create:[],update:[],delete:[],fields:[]}
};

function quote(id){return `"${String(id).replaceAll('"','""')}"`}
function parsePage(q){const limit=Math.min(Math.max(Number.parseInt(q.limit||'10',10)||10,1),100),offset=Math.max(Number.parseInt(q.offset||'0',10)||0,0);return{limit,offset}}
function session(database,request){const role=request.get('x-role')||String(request.query.role||'platform');if(!allRoles.includes(role))throw new HttpError(403,'未知角色');const row=database.prepare(`SELECT o.id org_id,o.org_name,o.org_type,r.role_name,u.display_name FROM sys_role r JOIN sys_user_role ur ON ur.role_id=r.id JOIN sys_user u ON u.id=ur.user_id JOIN sys_org o ON o.id=u.org_id WHERE r.role_code=? LIMIT 1`).get(role);if(!row)throw new HttpError(403,'角色尚未配置');return{role,...row}}
function requireResource(name){const cfg=resources[name];if(!cfg)throw new HttpError(404,'业务资源不存在');return cfg}
function can(list,role){return list.includes(role)}
function providerRole(role){return providers.includes(role)}
function scopeSql(cfg,s,{forWrite=false}={}){
  if(s.role==='platform'||(cfg.publicRead&&!forWrite))return{where:'',params:[]};
  const key=s.role==='trader'?cfg.scope?.trader:providerRole(s.role)?cfg.scope?.provider:null;
  if(cfg.owner)return{where:`${quote(cfg.owner)}=?`,params:[s.org_id]};
  if(key&&!["demand","party","orderTrader","eventOrderTrader","responsibleOrReporter","conversionRule","productProvider"].includes(key))return{where:`${quote(key)}=?`,params:[s.org_id]};
  if(key==='demand')return{where:'demand_id IN (SELECT id FROM mm_transport_demand WHERE trader_org_id=?)',params:[s.org_id]};
  if(key==='party')return{where:'id IN (SELECT order_id FROM mm_order_party WHERE org_id=?)',params:[s.org_id]};
  if(key==='orderTrader')return{where:'order_id IN (SELECT id FROM mm_transport_order WHERE trader_org_id=?)',params:[s.org_id]};
  if(key==='eventOrderTrader')return{where:'order_id IN (SELECT id FROM mm_transport_order WHERE trader_org_id=?)',params:[s.org_id]};
  if(key==='responsibleOrReporter')return{where:'(responsible_org_id=? OR reporter_org_id=?)',params:[s.org_id,s.org_id]};
  if(key==='conversionRule')return{where:'rule_id IN (SELECT id FROM tds_conversion_rule WHERE org_id=?)',params:[s.org_id]};
  if(key==='productProvider')return{where:'product_id IN (SELECT id FROM tds_data_product WHERE org_id=?)',params:[s.org_id]};
  if(cfg.ownerVia==='connector')return{where:'connector_id IN (SELECT id FROM tds_connector WHERE org_id=?)',params:[s.org_id]};
  return{where:'1=0',params:[]};
}
function rowById(db,cfg,id){return db.prepare(`SELECT * FROM ${quote(cfg.table)} WHERE id=?`).get(id)}
function assertOwned(db,cfg,id,s){const scope=scopeSql(cfg,s,{forWrite:true});const sql=`SELECT id FROM ${quote(cfg.table)} WHERE id=?${scope.where?` AND (${scope.where})`:''}`;if(!db.prepare(sql).get(id,...scope.params))throw new HttpError(404,'记录不存在或无权访问')}
function normalizeBody(cfg,body,s,creating){const result={};for(const f of cfg.fields){if(Object.hasOwn(body,f.name)){let value=body[f.name];if(f.type==='number')value=value===''?null:Number(value);if(f.type==='boolean')value=value?1:0;result[f.name]=value}}if(creating&&cfg.owner)result[cfg.owner]=s.org_id;if(creating&&cfg.scope?.trader==='applicant_org_id')result.applicant_org_id=s.org_id;if(creating&&cfg.table==='mm_exception')result.reporter_org_id=s.org_id;return result}
function validateRelations(db,cfg,values,s){if(s.role==='trader'&&cfg.table==='tds_access_request'){const product=db.prepare('SELECT org_id FROM tds_data_product WHERE id=?').get(values.product_id);if(!product||Number(product.org_id)!==Number(values.provider_org_id))throw new HttpError(400,'数据产品与提供方不匹配');if(values.demand_id&&!db.prepare('SELECT id FROM mm_transport_demand WHERE id=? AND trader_org_id=?').get(values.demand_id,s.org_id))throw new HttpError(403,'只能关联本企业运输需求')}if(!providerRole(s.role))return;if(values.connector_id!==undefined&&!db.prepare('SELECT id FROM tds_connector WHERE id=? AND org_id=?').get(values.connector_id,s.org_id))throw new HttpError(403,'只能关联本企业连接器');if(values.source_id!==undefined&&!db.prepare('SELECT ds.id FROM tds_data_source ds JOIN tds_connector c ON c.id=ds.connector_id WHERE ds.id=? AND c.org_id=?').get(values.source_id,s.org_id))throw new HttpError(403,'只能关联本企业数据源');if(values.resource_id!==undefined&&!db.prepare('SELECT id FROM tds_data_resource WHERE id=? AND org_id=?').get(values.resource_id,s.org_id))throw new HttpError(403,'只能关联本企业数据资源')}
function assertLifecycle(cfg,row,operation,s){if(!row)return;if(s.role==='trader'&&cfg.table==='mm_transport_demand'&&!['草稿','已撤回','已取消'].includes(row.status))throw new HttpError(409,'已进入执行流程的运输需求不能直接编辑或删除');if(s.role==='trader'&&cfg.table==='tds_access_request'&&!['草稿','已撤回','待补充材料'].includes(row.status))throw new HttpError(409,'当前状态的数据申请不能直接编辑或删除');if(operation==='delete'&&cfg.table==='tds_data_product'&&row.status==='已上架')throw new HttpError(409,'已上架数据产品请先下架');if(operation==='delete'&&cfg.table==='tds_conversion_rule'&&row.status==='启用')throw new HttpError(409,'启用中的转换规则请先停用');if(operation==='update'&&cfg.table==='mm_exception'&&row.status==='已关闭')throw new HttpError(409,'已关闭异常不能继续编辑')}
function audit(db,s,module,action,targetType,targetId,detail){db.prepare('INSERT INTO sys_operation_log(role_code,org_id,user_name,module,action,target_type,target_id,detail) VALUES(?,?,?,?,?,?,?,?)').run(s.role,s.org_id,s.display_name,module,action,targetType,targetId,String(detail||''))}
function code(prefix){return `${prefix}-${Date.now()}-${Math.floor(Math.random()*900+100)}`}

export function createBusinessRouter({database}){
  const router=Router();
  router.use((req,res,next)=>{try{req.session=session(database,req);res.set('Cache-Control','no-store');next()}catch(e){next(e)}});
  router.get('/session',(req,res)=>res.json({item:req.session}));
  router.get('/resources',(req,res)=>{const items=Object.entries(resources).filter(([,c])=>can(c.read,req.session.role)).map(([id,c])=>({id,title:c.title,canCreate:can(c.create,req.session.role),canUpdate:can(c.update,req.session.role),canDelete:can(c.delete,req.session.role)}));res.json({items,total:items.length})});
  router.get('/:resource/meta',(req,res)=>{const c=requireResource(req.params.resource);if(!can(c.read,req.session.role))throw new HttpError(403,'无查看权限');res.json({item:{title:c.title,fields:c.fields,canCreate:can(c.create,req.session.role),canUpdate:can(c.update,req.session.role),canDelete:can(c.delete,req.session.role)}})});
  router.get('/:resource',(req,res)=>{const c=requireResource(req.params.resource),s=req.session;if(!can(c.read,s.role))throw new HttpError(403,'无查看权限');const {limit,offset}=parsePage(req.query),search=String(req.query.search||'').trim(),scope=scopeSql(c,s),clauses=[],params=[];if(scope.where){clauses.push(`(${scope.where})`);params.push(...scope.params)}if(search&&c.search.length){clauses.push(`(${c.search.map(x=>`CAST(${quote(x)} AS TEXT) LIKE ?`).join(' OR ')})`);params.push(...c.search.map(()=>`%${search}%`))}const where=clauses.length?` WHERE ${clauses.join(' AND ')}`:'';const total=database.prepare(`SELECT COUNT(*) count FROM ${quote(c.table)}${where}`).get(...params).count;const items=database.prepare(`SELECT * FROM ${quote(c.table)}${where} ORDER BY id DESC LIMIT ? OFFSET ?`).all(...params,limit,offset);res.json({items,total,limit,offset})});
  router.get('/:resource/:id',(req,res)=>{const c=requireResource(req.params.resource);if(!can(c.read,req.session.role))throw new HttpError(403,'无查看权限');assertOwned(database,c,req.params.id,req.session);res.json({item:rowById(database,c,req.params.id)})});
  router.post('/:resource',(req,res)=>{const c=requireResource(req.params.resource),s=req.session;if(!can(c.create,s.role))throw new HttpError(403,'无新增权限');const values=normalizeBody(c,req.body||{},s,true);for(const f of c.fields.filter(x=>x.required)){if(values[f.name]===undefined||values[f.name]===null||values[f.name]==='')throw new HttpError(400,`${f.label}不能为空`)}validateRelations(database,c,values,s);const names=Object.keys(values);const result=database.prepare(`INSERT INTO ${quote(c.table)}(${names.map(quote).join(',')}) VALUES(${names.map(()=>'?').join(',')})`).run(...Object.values(values));audit(database,s,c.title,'新增',req.params.resource,result.lastInsertRowid,JSON.stringify(values));res.status(201).json({item:rowById(database,c,result.lastInsertRowid)})});
  router.patch('/:resource/:id',(req,res)=>{const c=requireResource(req.params.resource),s=req.session;if(!can(c.update,s.role))throw new HttpError(403,'无编辑权限');assertOwned(database,c,req.params.id,s);const current=rowById(database,c,req.params.id);assertLifecycle(c,current,'update',s);const values=normalizeBody(c,req.body||{},s,false);if(Object.keys(values).length===0)throw new HttpError(400,'没有可更新字段');validateRelations(database,c,values,s);if(current?.updated_at!==undefined)values.updated_at=new Date().toISOString();const names=Object.keys(values);database.prepare(`UPDATE ${quote(c.table)} SET ${names.map(x=>`${quote(x)}=?`).join(',')} WHERE id=?`).run(...Object.values(values),req.params.id);audit(database,s,c.title,'编辑',req.params.resource,req.params.id,JSON.stringify(values));res.json({item:rowById(database,c,req.params.id)})});
  router.delete('/:resource/:id',(req,res)=>{const c=requireResource(req.params.resource),s=req.session;if(!can(c.delete,s.role))throw new HttpError(403,'无删除权限');assertOwned(database,c,req.params.id,s);assertLifecycle(c,rowById(database,c,req.params.id),'delete',s);database.prepare(`DELETE FROM ${quote(c.table)} WHERE id=?`).run(req.params.id);audit(database,s,c.title,'删除',req.params.resource,req.params.id,'删除业务记录');res.status(204).end()});
  router.use((e,req,res,next)=>{if(!(e instanceof HttpError))return next(e);res.status(e.status).json({error:'Business Error',message:e.message})});
  return router;
}

export function createWorkflowRouter({database}){
  const router=Router();router.use((req,res,next)=>{try{req.session=session(database,req);next()}catch(e){next(e)}});
  router.get('/status',(req,res)=>{const demand=database.prepare("SELECT * FROM mm_transport_demand WHERE demand_no='DEM-2026-0001'").get();const requests=database.prepare('SELECT status,COUNT(*) count FROM tds_access_request WHERE demand_id=? GROUP BY status').all(demand.id);const scheme=database.prepare('SELECT * FROM mm_transport_scheme WHERE demand_id=? ORDER BY id DESC LIMIT 1').get(demand.id);const order=scheme?database.prepare('SELECT * FROM mm_transport_order WHERE scheme_id=?').get(scheme.id):null;const tasks=order?database.prepare('SELECT * FROM mm_task WHERE order_id=? ORDER BY segment_no').all(order.id):[];res.json({item:{demand,requests,scheme,order,tasks}})});
  router.post('/submit-request',(req,res)=>{const s=req.session;if(s.role!=='trader')throw new HttpError(403,'仅贸易商可提交数据申请');const row=database.prepare("SELECT * FROM tds_access_request WHERE id=? AND applicant_org_id=? AND status IN ('草稿','已撤回')").get(req.body.requestId,s.org_id);if(!row)throw new HttpError(409,'仅草稿或已撤回申请可以提交');database.prepare("UPDATE tds_access_request SET status='待审批',updated_at=CURRENT_TIMESTAMP WHERE id=?").run(row.id);audit(database,s,'数据申请','提交','request',row.id,'提交提供方审批');res.json({message:'数据申请已提交'})});
  router.post('/withdraw-request',(req,res)=>{const s=req.session;if(s.role!=='trader')throw new HttpError(403,'仅贸易商可撤回数据申请');const row=database.prepare("SELECT * FROM tds_access_request WHERE id=? AND applicant_org_id=? AND status='待审批'").get(req.body.requestId,s.org_id);if(!row)throw new HttpError(409,'仅待审批申请可以撤回');database.prepare("UPDATE tds_access_request SET status='已撤回',updated_at=CURRENT_TIMESTAMP WHERE id=?").run(row.id);audit(database,s,'数据申请','撤回','request',row.id,'申请人主动撤回');res.json({message:'数据申请已撤回'})});
  router.post('/withdraw-demand',(req,res)=>{const s=req.session;if(s.role!=='trader')throw new HttpError(403,'仅贸易商可撤回运输需求');const row=database.prepare("SELECT * FROM mm_transport_demand WHERE id=? AND trader_org_id=? AND status IN ('已提交','方案生成中')").get(req.body.demandId,s.org_id);if(!row)throw new HttpError(409,'当前运输需求不可撤回');database.prepare("UPDATE mm_transport_demand SET status='已撤回',updated_at=CURRENT_TIMESTAMP WHERE id=?").run(row.id);audit(database,s,'运输需求','撤回','demand',row.id,'贸易商撤回需求');res.json({message:'运输需求已撤回'})});
  router.post('/authorization-action',(req,res)=>{const s=req.session;if(!providerRole(s.role))throw new HttpError(403,'仅数据提供方可管理授权');const row=database.prepare('SELECT * FROM tds_authorization WHERE id=? AND provider_org_id=?').get(req.body.authorizationId,s.org_id);if(!row)throw new HttpError(404,'授权记录不存在');if(req.body.action==='extend'){database.prepare("UPDATE tds_authorization SET valid_to=datetime(COALESCE(valid_to,'now'),'+30 day'),status='生效中' WHERE id=?").run(row.id);audit(database,s,'数据授权','延长有效期','authorization',row.id,'延长30天');return res.json({message:'授权有效期已延长30天'})}if(req.body.action==='revoke'){database.prepare("UPDATE tds_authorization SET status='已撤销' WHERE id=?").run(row.id);audit(database,s,'数据授权','撤销','authorization',row.id,'提供方撤销授权');return res.json({message:'授权已撤销'})}throw new HttpError(400,'不支持的授权操作')});
  router.post('/close-exception',(req,res)=>{const s=req.session;if(s.role==='platform')throw new HttpError(403,'平台管理员仅监管异常');const scope=providerRole(s.role)?'(responsible_org_id=? OR reporter_org_id=?)':'reporter_org_id=?',params=providerRole(s.role)?[s.org_id,s.org_id]:[s.org_id];const row=database.prepare(`SELECT * FROM mm_exception WHERE id=? AND ${scope} AND status!='已关闭'`).get(req.body.exceptionId,...params);if(!row)throw new HttpError(404,'可处理异常不存在');database.prepare("UPDATE mm_exception SET status='已关闭',handling_comment=?,updated_at=CURRENT_TIMESTAMP WHERE id=?").run(req.body.comment||'协同事项已处理并确认关闭',row.id);audit(database,s,'异常协同','关闭','exception',row.id,req.body.comment||'');res.json({message:'异常已关闭'})});
  router.post('/submit-demand',(req,res)=>{const s=req.session;if(s.role!=='trader')throw new HttpError(403,'仅贸易商可提交需求');const d=database.prepare('SELECT * FROM mm_transport_demand WHERE id=? AND trader_org_id=?').get(req.body.demandId,s.org_id);if(!d)throw new HttpError(404,'需求不存在');if(!['草稿','已取消','已撤回'].includes(d.status))throw new HttpError(409,'当前状态不可提交');database.prepare("UPDATE mm_transport_demand SET status='已提交',updated_at=CURRENT_TIMESTAMP WHERE id=?").run(d.id);audit(database,s,'运输需求','提交','demand',d.id,'进入数据申请环节');res.json({message:'需求已提交',item:{...d,status:'已提交'}})});
  router.post('/apply-data',(req,res)=>{const s=req.session;if(s.role!=='trader')throw new HttpError(403,'仅贸易商可申请数据');const d=database.prepare("SELECT * FROM mm_transport_demand WHERE id=? AND trader_org_id=? AND status IN ('已提交','方案生成中')").get(req.body.demandId,s.org_id);if(!d)throw new HttpError(409,'请先提交运输需求');const products=database.prepare("SELECT * FROM tds_data_product WHERE status='已上架' ORDER BY id").all();for(const p of products){const exists=database.prepare('SELECT id FROM tds_access_request WHERE demand_id=? AND product_id=?').get(d.id,p.id);if(!exists)database.prepare("INSERT INTO tds_access_request(request_no,applicant_org_id,provider_org_id,product_id,demand_id,purpose,status) VALUES(?,?,?,?,?,'生成北粮南运联运方案','待审批')").run(code('REQ'),s.org_id,p.org_id,p.id,d.id)}database.prepare("UPDATE mm_transport_demand SET status='方案生成中',updated_at=CURRENT_TIMESTAMP WHERE id=?").run(d.id);audit(database,s,'数据申请','批量申请','demand',d.id,`申请${products.length}项联运协同数据`);res.status(201).json({message:`已提交${products.length}项数据申请`})});
  router.post('/approve-request',(req,res)=>{const s=req.session;if(!providerRole(s.role))throw new HttpError(403,'仅数据提供方可审批');const r=database.prepare("SELECT * FROM tds_access_request WHERE id=? AND provider_org_id=? AND status='待审批'").get(req.body.requestId,s.org_id);if(!r)throw new HttpError(404,'待审批申请不存在');const decision=req.body.decision==='reject'?'已驳回':req.body.decision==='supplement'?'待补充材料':'已通过',comment=req.body.comment||(decision==='已通过'?'同意按最小必要范围授权':decision==='待补充材料'?'请补充关联需求和使用范围说明':'业务用途或范围不符合要求');database.prepare('UPDATE tds_access_request SET status=?,review_comment=?,updated_at=CURRENT_TIMESTAMP WHERE id=?').run(decision,comment,r.id);if(decision==='已通过'){database.prepare("INSERT INTO tds_authorization(authorization_no,request_id,provider_org_id,consumer_org_id,product_id,demand_id,status,valid_to,allow_query,allow_subscribe) VALUES(?,?,?,?,?,?,'生效中',datetime('now','+30 day'),1,1)").run(code('AUTH'),r.id,r.provider_org_id,r.applicant_org_id,r.product_id,r.demand_id)}audit(database,s,'授权审批',decision,'request',r.id,comment);res.json({message:`申请${decision}`})});
  router.post('/generate-scheme',(req,res)=>{const s=req.session;if(s.role!=='trader')throw new HttpError(403,'仅贸易商可生成方案');const d=database.prepare('SELECT * FROM mm_transport_demand WHERE id=? AND trader_org_id=?').get(req.body.demandId,s.org_id);if(!d)throw new HttpError(404,'需求不存在');const auths=database.prepare("SELECT * FROM tds_authorization WHERE demand_id=? AND consumer_org_id=? AND status='生效中'").all(d.id,s.org_id);if(auths.length<4)throw new HttpError(409,`联运数据授权尚未完成（${auths.length}/4）`);let scheme=database.prepare('SELECT * FROM mm_transport_scheme WHERE demand_id=? ORDER BY id DESC LIMIT 1').get(d.id);if(!scheme){const result=database.prepare("INSERT INTO mm_transport_scheme(scheme_no,demand_id,scheme_name,route_summary,estimated_hours,estimated_cost,risk_level,recommendation_reason,status) VALUES(?,?, '公铁港海协同方案','绥化粮库→哈尔滨铁路站→营口港→广东目的港',168,2180000,'低','公路、铁路、港口及海运能力满足5,000吨运输需求，授权数据均在有效期内','待确认')").run(code('SCH'),d.id);scheme=database.prepare('SELECT * FROM mm_transport_scheme WHERE id=?').get(result.lastInsertRowid);const orgs=database.prepare("SELECT id,org_type FROM sys_org WHERE org_type IN ('车队企业','铁路企业','港口企业','船商企业') ORDER BY id").all();const types=['公路运输','铁路运输','港口协同','海运运输'],points=[['黑龙江绥化粮库','哈尔滨铁路站'],['哈尔滨铁路站','营口港站'],['营口港站','营口港装船泊位'],['营口港','广东目的港']];orgs.forEach((o,i)=>database.prepare('INSERT INTO mm_scheme_segment(scheme_id,segment_no,segment_type,carrier_org_id,origin,destination,estimated_cost) VALUES(?,?,?,?,?,?,?)').run(scheme.id,i+1,types[i],o.id,points[i][0],points[i][1],[180000,620000,280000,1100000][i]));for(const a of auths){database.prepare("INSERT INTO mm_data_reference(scheme_id,authorization_id,product_id,provider_org_id,influence) VALUES(?,?,?,?, '用于校验可用能力、作业窗口与预计成本')").run(scheme.id,a.id,a.product_id,a.provider_org_id);database.prepare("INSERT INTO tds_data_usage_log(authorization_id,product_id,consumer_org_id,user_name,use_purpose,call_method,result_count,call_status) VALUES(?,?,?,?,?,'API查询',1,'成功')").run(a.id,a.product_id,s.org_id,s.display_name,'生成联运方案')}}database.prepare("UPDATE mm_transport_demand SET status='待确认',updated_at=CURRENT_TIMESTAMP WHERE id=?").run(d.id);audit(database,s,'联运方案','生成','scheme',scheme.id,'使用已授权联运数据生成方案');res.status(201).json({message:'联运方案已生成',item:scheme})});
  router.post('/confirm-scheme',(req,res)=>{const s=req.session;if(s.role!=='trader')throw new HttpError(403,'仅贸易商可确认方案');const scheme=database.prepare("SELECT sc.* FROM mm_transport_scheme sc JOIN mm_transport_demand d ON d.id=sc.demand_id WHERE sc.id=? AND d.trader_org_id=? AND sc.status='待确认'").get(req.body.schemeId,s.org_id);if(!scheme)throw new HttpError(404,'待确认方案不存在');const d=database.prepare('SELECT * FROM mm_transport_demand WHERE id=?').get(scheme.demand_id);const result=database.prepare("INSERT INTO mm_transport_order(order_no,demand_id,scheme_id,trader_org_id,cargo_name,quantity_tons,origin,destination,estimated_arrival,total_cost,status) VALUES(?,?,?,?,?,?,?,?,?,?, '待执行')").run(code('MTO'),d.id,scheme.id,s.org_id,d.cargo_name,d.quantity_tons,d.origin,d.destination,d.expected_arrival,scheme.estimated_cost);const order=database.prepare('SELECT * FROM mm_transport_order WHERE id=?').get(result.lastInsertRowid),segments=database.prepare('SELECT * FROM mm_scheme_segment WHERE scheme_id=? ORDER BY segment_no').all(scheme.id);database.prepare("INSERT INTO mm_order_party(order_id,org_id,party_role) VALUES(?,?,'贸易商')").run(order.id,s.org_id);for(const seg of segments){database.prepare('INSERT INTO mm_order_party(order_id,org_id,party_role) VALUES(?,?,?)').run(order.id,seg.carrier_org_id,seg.segment_type);database.prepare("INSERT INTO mm_task(task_no,order_id,segment_no,task_type,responsible_org_id,origin,destination,planned_start,planned_end,status) VALUES(?,?,?,?,?,?,?,?,?,'待确认')").run(code('TASK'),order.id,seg.segment_no,seg.segment_type,seg.carrier_org_id,seg.origin,seg.destination,seg.planned_start,seg.planned_end)}database.prepare("UPDATE mm_transport_scheme SET status='已确认',updated_at=CURRENT_TIMESTAMP WHERE id=?").run(scheme.id);database.prepare("UPDATE mm_transport_demand SET status='已转订单',updated_at=CURRENT_TIMESTAMP WHERE id=?").run(d.id);audit(database,s,'联运方案','确认','order',order.id,'生成运输订单和四段任务');res.status(201).json({message:'方案已确认，已生成运输订单和四段任务',item:order})});
  router.post('/confirm-task',(req,res)=>{const s=req.session;if(!providerRole(s.role))throw new HttpError(403,'仅承运主体可确认任务');const task=database.prepare("SELECT * FROM mm_task WHERE id=? AND responsible_org_id=? AND status='待确认'").get(req.body.taskId,s.org_id);if(!task)throw new HttpError(404,'待确认任务不存在');database.prepare("UPDATE mm_task SET status='待执行',updated_at=CURRENT_TIMESTAMP WHERE id=?").run(task.id);audit(database,s,'分段任务','确认','task',task.id,task.task_type);res.json({message:'任务已确认'})});
  router.post('/execute-task',(req,res)=>{const s=req.session;if(!providerRole(s.role))throw new HttpError(403,'仅承运主体可执行任务');const task=database.prepare("SELECT * FROM mm_task WHERE id=? AND responsible_org_id=? AND status IN ('待执行','执行中')").get(req.body.taskId,s.org_id);if(!task)throw new HttpError(404,'可执行任务不存在');const progress=Math.min(Math.max(Number(req.body.progress||100),1),100),status=progress>=100?'已完成':'执行中',eventNo=code('EVT'),eventType=req.body.eventType||`${task.task_type}${status}`;database.prepare("UPDATE mm_task SET status=?,progress=?,actual_start=COALESCE(actual_start,CURRENT_TIMESTAMP),actual_end=CASE WHEN ?=100 THEN CURRENT_TIMESTAMP ELSE actual_end END,updated_at=CURRENT_TIMESTAMP WHERE id=?").run(status,progress,progress,task.id);const rule=database.prepare('SELECT id,biz_step,biz_status FROM tds_conversion_rule WHERE org_id=? ORDER BY id LIMIT 1').get(s.org_id);database.prepare("INSERT INTO tds_conversion_record(record_no,rule_id,source_record_no,source_status,epcis_event_no,event_type,transport_order_id,transport_task_id,validation_result,publish_status) VALUES(?,?,?,?,?,?,?,?,'通过','已发布')").run(code('CVR'),rule?.id,task.task_no,status,eventNo,eventType,task.order_id,task.id);const epcis=database.prepare("INSERT INTO tds_epcis_event(event_no,event_type,biz_step,biz_status,event_time,org_id,transport_order_id,transport_task_id,location_name,payload_json) VALUES(?,?,?,?,CURRENT_TIMESTAMP,?,?,?,?,?)").run(eventNo,eventType,rule?.biz_step||'shipping',rule?.biz_status||'in_transit',s.org_id,task.order_id,task.id,task.destination,JSON.stringify({taskNo:task.task_no,progress,status}));database.prepare("INSERT INTO mm_transport_event(event_no,order_id,task_id,event_type,event_time,location_name,source_org_id,epcis_event_id,description) VALUES(?,?,?, ?,CURRENT_TIMESTAMP,?,?,?,?)").run(code('MME'),task.order_id,task.id,eventType,task.destination,s.org_id,epcis.lastInsertRowid,req.body.description||'企业原系统状态经连接器转换为EPCIS事件');const remaining=database.prepare("SELECT COUNT(*) count FROM mm_task WHERE order_id=? AND status!='已完成'").get(task.order_id).count;database.prepare('UPDATE mm_transport_order SET status=?,updated_at=CURRENT_TIMESTAMP WHERE id=?').run(remaining===0?'已完成':'运输中',task.order_id);audit(database,s,'任务执行','上报事件','task',task.id,eventType);res.json({message:remaining===0?'全部分段完成，运输订单已完成':'任务事件已转换并发布',item:{taskId:task.id,status,progress,eventNo}})});
  router.use((e,req,res,next)=>{if(!(e instanceof HttpError))return next(e);res.status(e.status).json({error:'Workflow Error',message:e.message})});return router;
}
